// src/sections/Portfolio.jsx
import { useState } from 'react';
import { Container, SectionTitle, Link, Button, Project } from '@components';
import { projects } from '@api';
import _ from 'lodash';

const Portfolio = () => {
  const [filter, setFilter] = useState('all');

  const filteredProjects = () => {
    if (filter === 'all') return projects;

    return _.filter(projects, { type: filter });
  }
  
  return (
    <Container className='bg-platinum'>
      <div className='flex flex-col items-center'>
        <SectionTitle id='projects' text='Projects'/>
        <div className='text-center mb-6'>
          <span>{'A small collection of notable personal projects.'}</span>
          <div>
            <span>{'For more, check out my '}</span>
            <Link className='text-cornflower' href='https://github.com/alexbmoreira' target='_blank'>{'Github!'}</Link>
          </div>
        </div>
        <div className='flex justify-center w-full flex-wrap gap-2 mb-4'>
          <Button text='All' onSelect={() => setFilter('all')} selected={filter === 'all'}/>
          <Button text='Websites & Apps' onSelect={() => setFilter('app')} selected={filter === 'app'}/>
          <Button text='Packages' onSelect={() => setFilter('package')} selected={filter === 'package'}/>
          <Button text='Homelab' onSelect={() => setFilter('homelab')} selected={filter === 'homelab'}/>
        </div>
        <div className='flex flex-col w-full space-y-4'>
          {filteredProjects().map(project => <Project key={project.name} project={project}/>)}
        </div>
      </div>
    </Container>
  )
}

export default Portfolio

// src/components/portfolio/Portfolio.vue
<template>
  <div id="portfolio" class="bg-platinum flex">
    <div class="flex p-8 px-64 xl:px-24 md:px-12 flex-col sm:px-6">
      <div class="mx-auto mb-8 text-center">
        <span class="font-bold text-3xl border-b-2 border-steel">
          Portfolio
        </span>
        <p class="mt-3">A small collection of notable personal projects.</p>
        <p>
          For more, check out my
          <a
            class="text-cornflower hover:underline"
            href="https://github.com/alexbmoreira"
            target="_blank"
          >
            Github!
          </a>
        </p>
      </div>
      <Project
        v-for="(project, index) in projects"
        :name="project.name"
        :desc="project.desc"
        :github_link="project.github_link"
        :website="project.website"
        :stack="project.stack"
        :deploy="project.deploy"
        :image="project.image"
        :key="index"
      />
    </div>
  </div>
</template>

<script>
import Project from "./Project";
import projects from "@/api/projects";

export default {
  name: "Portfolio",
  components: {
    Project
  },
  data() {
    return {
      projects
    };
  }
};
</script>

<style></style>
