// src/components/about/About.vue
<template>
  <div id="about" class="bg-indigo flex">
    <div class="m-auto">
      <div class="flex p-8 px-64 xl:px-24 md:px-12 md:flex-col sm:px-6">
        <div class="w-1/6 md:mx-auto md:w-1/4 sm:w-1/2">
          <img class="rounded-full" src="@/assets/images/headshot.jpg" alt="" />
        </div>
        <div class="pl-6 flex flex-col w-5/6 md:pl-0 md:w-full">
          <h1 class="text-2xl font-bold text-snow">About Me</h1>
          <p class="text-platinum text-justify">
            As a software developer with three years of experience working with
            Ruby on Rails and React, I've built a strong foundation in modern
            web front-end and back-end development. I am passionate about
            computing and am always looking for ways to improve and expand my
            knowledge and skills. In my current role, I have successfully
            developed and delivered a number of complex projects, and I am
            excited to continue learning and growing in my field.
          </p>
          <h1 class="text-2xl font-bold text-snow pt-3">Contact</h1>
          <div class="flex flex-col text-platinum">
            <a href="mailto:alexbmoreira@gmail.com">
              <span class="transition duration-400 ease-in-out hover:text-snow">
                <i class="fas fa-envelope mr-2"></i>alexbmoreira@gmail.com
              </span>
            </a>
            <a href="tel:+14164336886">
              <span class="transition duration-400 ease-in-out hover:text-snow">
                <i class="fas fa-phone-alt mr-2"></i>(416) 433-6886
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "About",
  data() {
    return {};
  }
};
</script>

<style scoped></style>

// src/sections/About.jsx
import headshot from '@assets/headshot.jpg';
import { Link } from '@components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const Bio = () => {
  return (
    <div>
      <div className='text-2xl mb-3 text-center font-semibold md:text-left'>{'About Me'}</div>
      <div className='text-justify md:text-left'>
        {"As a software developer with three years of experience working with Ruby on Rails and React, I've built a strong foundation in modern web front-end and back-end development. I am passionate about computing and am always looking for ways to improve and expand my knowledge and skills. In my current role, I have successfully developed and delivered a number of complex projects, and I am excited to continue learning and growing in my field."}
      </div>
    </div>
  )
}

const Contact = () => {
  return (
    <div>
      <div className='text-2xl mb-3 text-center font-semibold md:text-left'>{'Contact'}</div>
      <div className='flex flex-col space-y-2'>
        <Link href='mailto:alexbmoreira@gmail.com'>
          <FontAwesomeIcon icon='fa-solid fa-envelope'/>
          <span className='ml-2'>{'alexbmoreira@gmail.com'}</span>
        </Link>
        <Link href='tel:+14164336886'>
          <FontAwesomeIcon icon='fa-solid fa-phone'/>
          <span className='ml-2'>{'(416) 433-6886'}</span>
        </Link>
      </div>
    </div>
  )
}

const About = () => {
  return (
    <div id='about' className='flex flex-col items-center bg-indigo text-snow p-8 md:flex-row md:px-32'>
      <div className='w-1/2 md:w-1/4 lg:w-1/6'>
        <img className='rounded-full' src={headshot} alt='A picture of me'/>
      </div>
      <div className='flex flex-col mt-4 space-y-4 w-full lg:w-5/6 md:w-3/4 md:ml-8 md:mt-0'>
        <Bio/>
        <Contact/>
      </div>
    </div>
  )
}

export default About
