// src/components/Footer.vue
<template>
  <div class="relative flex bg-black p-8">
    <div class="text-gray-700 flex flex-col m-auto">
      <div class="mx-auto mt-2 text-2xl justify-around space-x-16 flex w-9/12 md:text-3xl">
        <a href="https://github.com/alexbmoreira" class="text-center hover:text-white">
          <i class="fab fa-github"></i>
        </a>
        <a href="https://www.linkedin.com/in/alexbmoreira" class="text-center hover:text-white">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="text-center hover:text-white">
          <i class="fas fa-file-pdf"></i>
        </a>
      </div>
      <div class="text-center mt-3">
        <p>Alex Moreira</p>
        <a href="mailto:alexbmoreira@gmail.com"><p class="hover:text-white">alexbmoreira@gmail.com</p></a>
        <a href="tel:+14164336886"><p class="hover:text-white">(416) 433-6886</p></a>
      </div>
    </div>
  </div>
</template>

<script>
export default {
    name: "Footer",
    data() {
        return {
            
        }
    },
}
</script>

<style>
    
</style>

// src/sections/Footer.jsx
import { Link } from '@components'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

const Footer = () => {
  return (
    <div className='flex flex-col justify-center items-center bg-midnight text-snow p-6'>
      <div className='text-sm mb-2'>{'Alex Moreira'}</div>
      <div className='flex space-x-6'>
        <Link href='https://linkedin.com/in/alexbmoreira/'>
          <FontAwesomeIcon icon='fa-brands fa-linkedin'/>
        </Link>
        <Link href='https://github.com/alexbmoreira/'>
          <FontAwesomeIcon icon='fa-brands fa-github'/>
        </Link>
        <Link href='/Alex_Moreira_Resume.pdf' download>
          <FontAwesomeIcon icon='fa-solid fa-file-user'/>
        </Link>
      </div>
    </div>
  )
}

export default Footer
